### ISSUE TITLE
compilation fails on kernel 6.4 with nvidia 340

### ISSUE THREAD

**Issue by mx1up** [dkosmari/nvidia-340.108-updated#2]
Hi,

thanks for the patch. Compilation fails however on opensuse 15.6:

```
DKMS make.log for nvidia-340.108 for kernel 6.4.0-150600.23.33-default (x86_64)
zo 16 mrt 2025 19:27:24 CET
make[1]: Entering directory '/var/lib/dkms/nvidia/340.108/build'
touch .nv-kernel.o.cmd
make -C /lib/modules/6.4.0-150600.23.33-default/build M=/var/lib/dkms/nvidia/340.108/build/
make[2]: Entering directory '/var/lib/dkms/nvidia/340.108/build'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  CC [M]  /var/lib/dkms/nvidia/340.108/build/nv-acpi.o
In file included from /var/lib/dkms/nvidia/340.108/build/nv-acpi.c:15:0:
/var/lib/dkms/nvidia/340.108/build/nv-linux.h: In function ‘NV_GET_USER_PAGES’:
/var/lib/dkms/nvidia/340.108/build/nv-linux.h:2194:20: error: too many arguments to function ‘get_user_pages’
             return get_user_pages(start, nr_pages, flags, pages, vmas);
                    ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/nvidia/340.108/build/nv-linux.h:49:0,
                 from /var/lib/dkms/nvidia/340.108/build/nv-acpi.c:15:
/usr/src/linux-6.4.0-150600.23.33/include/linux/mm.h:2459:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-6.4.0-150600.23.33/scripts/Makefile.build:252: /var/lib/dkms/nvidia/340.108/build/nv-acpi.o] Error 1
make[2]: *** [../../../linux-6.4.0-150600.23.33/Makefile:2064: /var/lib/dkms/nvidia/340.108/build] Error 2
make[2]: Leaving directory '/usr/src/linux-6.4.0-150600.23.33-obj/x86_64/default'
make[1]: *** [Makefile:94: all] Error 2
make[1]: Leaving directory '/var/lib/dkms/nvidia/340.108/build'
```

i found [this related post on nvidia forum](https://forums.developer.nvidia.com/t/linux-4-4-172-nvidia-340-107-error-too-many-arguments-to-function-get-user-pages/70822) with the advice to "just update your driver". This driver is the latest my card supports :/

**Comment by kda2210** [comment]
Hello,

I'm happy to let you know that I was able to get the 340.108 driver working on kernel 6.11.

I've created a patch and started publishing information on GitHub. You're welcome to use it — here’s the link:
👉 https://github.com/kda2210/nvidia-340-ubuntu-24.04/

I'm writing to you from Russia. If my work is helpful to you, I would really appreciate it if you could help me in return by spreading the word about my project on English-speaking forums or websites. Unfortunately, my English is not good enough to do this effectively myself.

Thank you very much in advance!
